name: Backend CI/CD

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout Repository
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Set up JDK
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: 21
          distribution: 'temurin'

      # 3. Run Tests
      - name: Run tests with Maven
        run: mvn clean test

      # 4. Build Jar
      - name: Build with Maven
        run: mvn clean package

      # 5. Upload to S3
      - name: Upload Jar to S3
        run: |
          aws s3 cp ./target/payphone-backend-0.0.1-SNAPSHOT.jar s3://${{ secrets.DEPLOY_S3_BUCKET }}/
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}

      # 6. Trigger CodeDeploy Deployment
      - name: Deploy to EC2 with CodeDeploy
        run: |
          aws deploy create-deployment \
            --application-name ${{ secrets.DEPLOY_APPLICATION_NAME }} \
            --deployment-group-name ${{ secrets.DEPLOY_GROUP_NAME }} \
            --deployment-config-name CodeDeployDefault.OneAtATime \
            --s3-location bucket=${{ secrets.DEPLOY_S3_BUCKET }},key=payphone-backend-0.0.1-SNAPSHOT.jar,bundleType=zip
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
