name: Backend CD

on:
  push:
    branches:
      - main

env:
  AWS_REGION: ap-northeast-2
  S3_BUCKET_NAME: payphone-backend-deploy
  CODE_DEPLOY_APPLICATION_NAME: payphone_backend
  CODE_DEPLOY_DEPLOYMENT_GROUP_NAME: payphone-backend-group

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. 코드 체크아웃
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. JDK 설정
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: 21
          distribution: 'temurin'

      # 3. Maven 빌드 및 결과물 압축
      - name: Build and Zip
        run: |
          mvn clean package -DskipTests
          mkdir deploy
          cp ./target/*.jar ./deploy/
          zip -r -qq ./payphone-backend.zip ./deploy/

      # 4. S3 업로드
      - name: Upload Jar to S3
        run: |
          aws s3 cp ./payphone-backend.zip s3://$S3_BUCKET_NAME/
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      # 5. CodeDeploy 배포
      - name: Deploy to EC2 with CodeDeploy
        run: |
          aws deploy create-deployment \
            --application-name $CODE_DEPLOY_APPLICATION_NAME \
            --deployment-group-name $CODE_DEPLOY_DEPLOYMENT_GROUP_NAME \
            --deployment-config-name CodeDeployDefault.AllAtOnce \
            --s3-location bucket=$S3_BUCKET_NAME,key=payphone-backend.zip,bundleType=zip
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
